Feature book detail
wolox-training/ng-angularjs pull request #1
Opened 2021-03-08 22:17 UTC by ngilotti

## Summary
- Completed project setup
- Completed the layout of book details 

## Screenshot
![Captura de pantalla de 2021-03-08 19-09-30](https://user-images.githubusercontent.com/56491095/110388458-e64d7e80-8041-11eb-8634-c53b90561f14.png)

## Trello Card
https://trello.com/c/2IlIDmrC

2021-03-09 15:11 UTC, MMarussi requested changes
Nice job! After addressing some details it will be ready to merge :ok_hand:

2021-03-09 15:11 UTC, MMarussi commented on .gitignore
> +.DS_Store
Remember to add new lines at the end of files, for more info on why people do this checkout [this](https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file)
If you are using VScode there is a setting that does this automatically for you after saving the file!

2021-03-09 15:11 UTC, MMarussi commented on index.html
> +<head>
Indent this and the remaining lines inside of the `<html>` tag, remember to use 2 spaces to indent

2021-03-09 15:11 UTC, MMarussi commented on index.html
> +
There's no need to use a blank line to separate these divs

2021-03-09 15:11 UTC, MMarussi commented on scss/colors.scss
> +$red: #ff0000;
This is the only color whose hex is not uppercased. Uppercase it in order to mantain a standard between the colors, I swear i'm not being obsessive (?

2021-03-09 15:11 UTC, MMarussi commented on scss/detail.scss
> +.tag-rigth {
Little typo here `.tag-right`

2021-03-09 15:11 UTC, MMarussi commented on scss/detail.scss
> +}
There are 2 classes with different indentation. You can use 2 or 4 spaces (we usually use 2), but most importantly avoid mixing them

2021-03-09 15:11 UTC, MMarussi commented on scss/styles.scss
> +  .title {
Is this class being used in the project? If not it would be a good idea to remove this file so we have less code

2021-03-09 15:11 UTC, MMarussi commented on scss/detail.scss
> +.rectangle {
Try to use more descriptive names for these classes, I would use "container-main" or "container-book" or something like that, so it's clearer to the reader what's the purpose of the class

2021-03-09 15:11 UTC, MMarussi commented on scss/colors.scss
> +$swadow:  #00000080;
Did you mean $shadow? :thinking: 
Also the hex code can be simplified to `#000008`

2021-03-09 15:11 UTC, MMarussi commented on scss/detail.scss
> +  border-bottom: solid $green-lemon;
Just in case don't forget to specify the "border-width" with a width in px or another unit

2021-03-09 15:11 UTC, MMarussi commented on scss/detail.scss
> +    font-family: Roboto;
Maybe this font family is used all across the site, so it would be worthwhile to define a class to assign this attribute to all tags :wink:

2021-03-10 13:43 UTC, mcallegari10 requested changes

2021-03-10 13:43 UTC, mcallegari10 commented on scss/detail.scss
> +@import 'colors';
You can import the colors in the `application.scss` so you won't have to do it in every sass file you need those variables

2021-03-10 13:43 UTC, mcallegari10 commented on index.html
> +            <span class="title-book">Título del libro</span>
Should be an `h2` at least

2021-03-10 13:43 UTC, mcallegari10 commented on index.html
> +            <span class="title-gender">(género)</span>
This is an `h3` I think

2021-03-10 13:43 UTC, mcallegari10 commented on scss/detail.scss
> +.img {
Maybe `cover-image`is a better name 😄

2021-03-10 13:43 UTC, mcallegari10 commented on scss/detail.scss
> +  flex-direction: row;
This is the default value, so there's no need to specify

2021-03-10 14:40 UTC, mcallegari10 approved these changes

2021-03-10 15:14 UTC, merged