Feature book deatil III
wolox-training/ng-angularjs pull request #2
Opened 2021-03-09 20:33 UTC by ngilotti

## Summary
- added the image of the book.

## Screenshot
![Captura de pantalla de 2021-03-09 17-30-16](https://user-images.githubusercontent.com/56491095/110533901-39d0d280-80fd-11eb-9216-26774b4a3d54.png)

## Trello Card
https://trello.com/c/etQhnEsv
https://trello.com/c/BY1h8WiV

2021-03-10 19:07 UTC, MMarussi requested changes

2021-03-10 19:07 UTC, MMarussi commented on index.html
> +            <img class="cover-image img" src="./assets/book-cover.png" alt="img">
The `alt` attribute should give a clear description of the image. Try to use a text that gives the idea of what the image shows if for example it weren't there.
If you want a little bit more info about this, you can start with this [site](https://support.siteimprove.com/hc/en-gb/articles/115000013031-Accessibility-Image-Alt-text-best-practices)

2021-03-10 19:07 UTC, MMarussi commented on scss/detail.scss
> +.cover-image img {
The following styles will be applied to any img descendant of .cover-image. This is perfectly valid css, but since we are using sass, how about using sass nesting instead?

2021-03-10 19:07 UTC, MMarussi commented on index.html
> +            <img class="cover-image img" src="./assets/book-cover.png" alt="img">
In the file index.html the class `cover-image` is assigned to both the parent div and the image.
After a little peek in the .scss I think `cover-image` is unnecessary for the image element

2021-03-10 19:08 UTC, MMarussi commented on index.html
> +            <img class="cover-image img" src="./assets/book-cover.png" alt="img">
Related to [comment](https://github.com/wolox-training/ng-angularjs/pull/2#discussion_r591769201), The ".img" class is assigned to the img element but in the .scss only the img html tag is being targeted.

2021-03-10 21:13 UTC, MMarussi commented on scss/styles.scss
> +  position: absolute;
Is position: absolute necessary for the images?

2021-03-12 13:22 UTC, mcallegari10 approved these changes

2021-03-12 13:27 UTC, MMarussi approved these changes

2021-03-12 13:31 UTC, merged