Feature book navbar
wolox-training/ng-angularjs pull request #5
Opened 2021-03-12 13:17 UTC by ngilotti

## Summary
- added navBar to book list screen

## Screenshot
![Captura de pantalla de 2021-03-12 10-12-43](https://user-images.githubusercontent.com/56491095/110945090-04ee9680-831c-11eb-8171-04b81d3564d2.png)

## Trello Card
https://trello.com/c/oaZPlpvu

2021-03-15 20:42 UTC, MMarussi requested changes

2021-03-15 20:42 UTC, MMarussi commented on scss/book-list.scss
> +  justify-content: space-around
```suggestion
  justify-content: space-around;
```

2021-03-15 20:42 UTC, MMarussi commented on scss/detail.scss
> +  margin-top: 12%;
Keep in mind that percentages applied are based on the parent element width (.container-book parent's width)

2021-03-15 20:42 UTC, MMarussi commented on scss/styles.scss
> +  z-index: 100;
It works but 100 is a little bit excessive :laughing: Did you try with 1?

2021-03-15 20:42 UTC, MMarussi commented on scss/styles.scss
> +    display: flex;
This element does not have children, do we need flex here?

2021-03-15 20:42 UTC, MMarussi commented on scss/styles.scss
> +    margin-left: 599px;
Even though this can achieve the desired design I think that using flexbox on these elements parent will prove worthy in order to avoid defining those margins on the children. Spoiler (flexbox and justify-content: space-between should do the trick)

2021-03-15 20:42 UTC, MMarussi commented on scss/styles.scss
> +    display: flex;
Same as .nav-logo

2021-03-15 20:45 UTC, MMarussi commented on list.html
> +      <img class="nav-logo" src="./assets/LogoWolox.png" alt="Logo">
Regarding the alt, "Wolox logo" would be more descriptive :smile:

2021-03-16 18:00 UTC, MMarussi commented on scss/detail.scss
> +  height: 118.57px;
Remember to round up these decimals

2021-03-16 18:00 UTC, MMarussi commented on scss/book-list.scss
> +    position: relative;
Is the position necessary?

2021-03-17 15:14 UTC, MMarussi approved these changes

2021-03-17 18:42 UTC, mcallegari10 approved these changes

2021-03-17 18:42 UTC, mcallegari10 commented on scss/styles.scss
> +h6 {
Check the other h, try not to style HTML tags directly. Always use classes

2021-03-17 19:12 UTC, merged