Feature detail back arrow
wolox-training/ng-angularjs pull request #7
Opened 2021-03-15 19:53 UTC by ngilotti

## Summary
- return arrow added

## Screenshot
![Captura de pantalla de 2021-03-15 16-52-43](https://user-images.githubusercontent.com/56491095/111212885-efdd6600-85ae-11eb-90ea-8ee660fe1f25.png)

## Trello Card
https://trello.com/c/TyK8Tnld

2021-03-19 17:32 UTC, MMarussi requested changes

2021-03-19 17:32 UTC, MMarussi commented on index.html
> +      <div class="back-arrow">
In order to reduce the elements on the DOM have you tried to remove this div? I believe you can achieve the same results

2021-03-19 17:32 UTC, MMarussi commented on scss/detail.scss
> +    z-index: 100;
Use `z-index: 1;` there's no need to use big number on z-index

2021-03-19 17:32 UTC, MMarussi commented on scss/detail.scss
> +    width: auto;
I'm sure you can remove the `height` and `width` rules since `auto` is the default value for both

2021-03-19 17:32 UTC, MMarussi commented on scss/styles.scss
> +  justify-content: flex-start;
`flex-start` is the default value for `justify-content` so it can be removed without a problem

2021-03-23 16:03 UTC, MMarussi commented on scss/detail.scss
> +
This space is unnecessary

2021-03-23 16:03 UTC, MMarussi commented on scss/detail.scss
> +    cursor: pointer;
This rule is already defined at the base `.back-arrow` class, so you don't have to specify it again :wink:

2021-03-23 17:56 UTC, MMarussi approved these changes
Nice work! :muscle:

2021-03-30 17:03 UTC, mcallegari10 approved these changes

2021-03-30 17:03 UTC, mcallegari10 commented on index.html
> +      <h4 class="back-arrow">Atrás</h4>
This should be an `a` tag

2021-03-30 17:03 UTC, mcallegari10 commented on scss/detail.scss
> +.back-arrow::before {
The way we usually write pseudo-elements is 

```scss
.back-arrow {
  ...
  
  &::before {
    ...
  }
}
```

2021-03-30 18:46 UTC, merged